name: Deploy Backend

on:
  push:
    branches:
      - add_test_actions

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Swift
      uses: fwal/setup-swift@v1
      with:
        swift-version: '5'

    - name: Build and test Vapor app
      run: swift build -c release

    - name: Deploy to server
      uses: appleboy/scp-action@master
      with:
        host: dobodox.com
        username: github
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: ".build/release/Run"
        target: "/home/github/srv/cat_me_if_you_can"
        strip_components: 2
