name: Deploy Backend

on:
  push:
    branches:
      - deployed-websocket-test
      - main

jobs:
  build-and-deploy:
    runs-on: Ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Swift
      uses: fwal/setup-swift@v1
      with:
        swift-version: '5'

    - name: Build and test Vapor app
      working-directory: ./Backend
      run: swift build -c release

    - name: Deploy to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "Backend/.build/release/Run"
        target: "/home/github/srv/cat_me_if_you_can/build"
        strip_components: 3

    - name: Restart container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/github/srv/cat_me_if_you_can
          sudo docker compose restart
