name: Deploy Backend

on:
  push:
    branches:
      - add_test_actions

jobs:
  build-and-deploy:
    runs-on: Ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Swift
      uses: fwal/setup-swift@v1
      with:
        swift-version: '5'

    - name: Build and test Vapor app
      run: swift build
      
#    - name: Prepare Install Diectory
 #     run: |
  #      rm -rf .build/install
   #     mkdir -p .build/install
    #    cp -P .build/debug/Run .build/install/
     #   cp -P /usr/lib/swift/linux/lib*so* .build/install/
      

    - name: Deploy to server
      uses: appleboy/scp-action@master
      with:
        host: dobodox.com
        username: github
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: ".build/install/*"
        target: "/home/github/srv/cat_me_if_you_can/build"
        strip_components: 2
