name: Test Backend

on:
  push:
    branches: [ "add_test_actions" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Swift
      uses: fwal/setup-swift@v1
      with:
        swift-version: '5'

    - name: Get Swift Version
      run: swift --version

    - name: Build
      working-directory: ./Backend
      run: swift build
      
    - name: Run tests
      working-directory: ./Backend
      run: swift test


