name: Moose Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get Swift Version
      run: swift --version
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1.4.0
      with:
        xcode-version: "13.1"

